name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Run detekt
        run: ./gradlew detekt --continue

      - name: Run tests
        if: success() || failure()
        run: ./gradlew test


  validate-gradle-wrapper:
    runs-on: ubuntu-latest
    name: Validate Gradle Wrapper

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
